### ISSUE TITLE
Fail to load the `weather-app`, `city-service`, `gateway`, `weather-service` pages

### ISSUE THREAD

**Issue by zimuli157** [Azure-Samples/java-on-aca-quarkus#4]
**Description**

After running `azd up`, click the link of the `weather-app` service, the page is not as expected as follows:
![image](https://github.com/user-attachments/assets/4cc88d4a-0041-4f6a-9f63-5db61a4b6ed3)

- weather-app:

![image](https://github.com/user-attachments/assets/a95f7dc0-fc22-4728-b390-aea730f10de5)

In addition, the pages of the other three services cannot be loaded successfully, as follows:

- city-service:

![image](https://github.com/user-attachments/assets/3ba112bb-8295-40e8-9658-d8d6c0dc227e)

- gateway:

![image](https://github.com/user-attachments/assets/994da1ea-225e-4c37-897c-1497ecf9c886)

- weather-service:

![image](https://github.com/user-attachments/assets/e1a74fd7-b1ef-44e3-8aeb-afd20a4a93d7)

**Repro steps**
1. Run `azd auth login`.
2. Run `azd init --template Azure-Samples/java-on-aca-quarkus`.
3. Ensure that Docker is running in your environment.
4. Run `azd up`.
5. Click the service link.

**Environment**

- azd version 1.10.3 (commit 0595f33fe948ee6df3da492567e3e7943cb9a733)
- OS: Windows

**Expected behavior**
The `weather-app`, `city-service`, `gateway`, `weather-service` pages can be loaded successfully.

@majguo and @hemarina for notification.

**Comment by majguo** [comment]
@zimuli157 The root cause is that the shell scripts cloned to the windows system have a different end-of-line and can't be executed in a Linux container. Fixed in commit b65b6b0 which will force shell scripts cloned to windows system keep Linux required end-of-line. Pls create a new empty folder and retry your test steps, thanks.

Besides, pls only check `weather-app` page as it's a front-end app, safely ignore other services (endpoints for `city-service` and `weather-service` are not accessible as their ingresses are set to `internal`. Endpoint for `gateway` should be accessible but it just serves as an API gateway for `weather-app`). You can follow [Quickstart](https://github.com/Azure-Samples/java-on-aca-quarkus?tab=readme-ov-file#quickstart) as well.

**Comment by zimuli157** [comment]
It has been fixed and we will close this issue.
